name: DAFO Frontend NextJS

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: tuannqvnist
          password: dckr_pat_D8f1e65zcgkv_MuICyYJWKHFF2k
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./nextjs.Dockerfile
          push: true
          tags: |
            tuannqvnist/dafo-frontend:latest
            tuannqvnist/dafo-frontend:${{ steps.vars.outputs.sha_short }}
